on:
    pull_request: null
    push:
        branches:
            - '*.*'

name: cs

jobs:
    cs:
        uses: spiral/gh-actions/.github/workflows/cs.yml@master
        with:
            os: >-
                ['ubuntu-latest']
